# Generated by Django 4.1.3 on 2022-12-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('pays', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pays',
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('codeproduit', models.CharField(db_column='codeProduit', max_length=20, primary_key=True, serialize=False)),
                ('nomproduit', models.CharField(db_column='nomProduit', max_length=30)),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('nofacture', models.IntegerField(db_column='noFacture', primary_key=True, serialize=False)),
                ('datefacture', models.DateField(db_column='dateFacture')),
                ('pays', models.ForeignKey(db_column='pays', on_delete=django.db.models.deletion.CASCADE, to='ETL.pays')),
            ],
            options={
                'db_table': 'ventes',
            },
        ),
        migrations.CreateModel(
            name='Detailsventes',
            fields=[
                ('iddetails', models.AutoField(db_column='idDetails', primary_key=True, serialize=False)),
                ('codeproduit', models.ForeignKey(db_column='codeProduit', on_delete=django.db.models.deletion.CASCADE, to='ETL.produits')),
                ('nofacture', models.ForeignKey(db_column='noFacture', on_delete=django.db.models.deletion.CASCADE, to='ETL.ventes')),
            ],
            options={
                'db_table': 'detailsVentes',
                'unique_together': {('nofacture', 'codeproduit')},
            },
        ),
    ]
