# Generated by Django 4.1.3 on 2022-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='nomproduit',
            field=models.CharField(db_column='nomProduit', max_length=50),
        ),
    ]
