# Generated by Django 4.1.3 on 2022-12-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0002_alter_produits_nomproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtre',
            fields=[
                ('nfiltre', models.AutoField(db_column='nFiltre', primary_key=True, serialize=False)),
                ('filtrepays', models.CharField(blank=True, db_column='filtrePays', max_length=10, null=True)),
                ('filtredate', models.CharField(blank=True, db_column='filtreDate', max_length=10, null=True)),
                ('filtreproduits', models.CharField(blank=True, db_column='filtreProduits', max_length=10, null=True)),
            ],
            options={
                'db_table': 'filtre',
            },
        ),
    ]
