# Generated by Django 4.1.3 on 2022-12-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0003_filtre'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtre',
            name='filtretoppays',
            field=models.CharField(blank=True, db_column='filtreTopPays', max_length=10, null=True),
        ),
    ]
