# Generated by Django 4.1.3 on 2022-12-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0005_alter_filtre_filtretoppays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtre',
            name='filtreproduits',
            field=models.CharField(blank=True, db_column='filtreProduits', max_length=50, null=True),
        ),
    ]
